name: dsa-tools

services:
  dsa-tools:
    image: dsa-tools
    build: .
    restart: always
    ports:
      - "3333:3000"
    volumes:
      - ".docker/storage:/data/storage"
      - ".docker/data:/data/data"
